name: .NET CI

on:
  pull_request:
    branches: ["dev", "master"]
  push:
    branches: ["dev"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET preview SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"
          dotnet-quality: "preview"

      - name: Display .NET version
        run: dotnet --version

      - run: dotnet restore

      - run: dotnet build --no-restore --configuration Release

      - name: Run Unit Tests
        run: dotnet test DocumentIngestion.Unit.Tests/DocumentIngestion.Unit.Tests.csproj --framework net9.0 --verbosity normal


      - name: Run Integration Tests
        run: dotnet test DocumentIngestion.Integration.Tests/DocumentIngestion.Integration.Tests.csproj --framework net9.0 --verbosity normal
  sync-to-readme:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync OpenAPI spec to ReadMe
        uses: readmeio/rdme@v10
        with:
          rdme: openapi upload src/DocumentIngestion.Api/openapi.yaml \
                --key=${{ secrets.README_API_KEY }} \
                --id=${{ secrets.README_API_DEFINITION_ID }}
