name: .NET CI

on:
  pull_request:
    branches: ["dev", "master"]
  push:
    branches: ["dev"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET preview SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"
          dotnet-quality: "preview"

      - name: Display .NET version
        run: dotnet --version

      - run: dotnet restore

      - run: dotnet build --no-restore --configuration Release

      - run: dotnet test --no-build --verbosity normal
