name: .NET CI

on:
  pull_request:
    branches: [ "dev", "master" ]
  push:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install .NET 9 preview
      run: |
        wget https://dotnetcli.azureedge.net/dotnet/Sdk/<new-version>/dotnet-sdk-<new-version>-linux-x64.tar.gz
        mkdir -p $HOME/dotnet
        tar zxf dotnet-sdk-<new-version>-linux-x64.tar.gz -C $HOME/dotnet
        echo "$HOME/dotnet" >> $GITHUB_PATH
        echo "DOTNET_ROOT=$HOME/dotnet" >> $GITHUB_ENV

    - name: Verify .NET SDK Version
      run: dotnet --version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
